name: ServerSiteGenerator
version: '1.1'
main: nickawrist.server_Website.Server_Website
api-version: '1.21'
commands:
  serverweb:
    description: Open the server website
    usage: /serverweb reload
    aliases: [sw]
